name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  # Full build, test and coverage report workflow for Ubuntu and macOS
  build-unix:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v6

    - name: Install dependencies
      run: (which apt-get && sudo apt-get install perl lcov) || (which brew && brew install lcov) || echo

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON

    - name: Build
      run: cmake --build build

    - name: Run tests (optional tests excluded)
      run: ctest . -C Debug -LE optional
      working-directory: build

    - name: Process and upload coverage data
      run: |
        lcov --capture --directory . --output-file coverage.info --ignore-errors unsupported,unsupported,inconsistent,format,format
        lcov --remove coverage.info '/usr/*' --output-file coverage.info --ignore-errors unused,inconsistent,format
        lcov --remove coverage.info '/Applications/Xcode*.app/*' --output-file coverage.info --ignore-errors unused,inconsistent,format
        lcov --list coverage.info --ignore-errors inconsistent
        bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
      working-directory: build

    - name: Upload artifacts
      uses: ./.github/actions/upload-artifacts
      with:
        label: ${{ matrix.os }}

  # Build and test under Cygwin on Windows
  build-cygwin:
    runs-on: windows-latest

    steps:
    - name: Disable git autocrlf
      run: git config --global core.autocrlf false

    - name: Checkout source code
      uses: actions/checkout@v6

    - name: Install dependencies
      uses: cygwin/cygwin-install-action@v6
      with:
        packages: gcc-core gcc-g++ cmake ninja perl

    - name: Configure
      shell: bash
      run: cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      shell: bash
      run: cmake --build build

    - name: Run required tests (optional tests are excluded)
      shell: bash
      run: export PATH="$(pwd):$PATH" && ctest . -C Debug -LE optional
      working-directory: build

    - name: Upload artifacts
      uses: ./.github/actions/upload-artifacts
      with:
        label: windows-cygwin
        suffix: .exe
